/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import javax.swing.JOptionPane;

/**
 *
 * @author anonimo
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        for (int i = 0; i < posicion.length; i++) {
            posicion[i] = -1;
        }
    }

    private pizza pizza_ = new pizza();
    private int posicion[] = new int[4];
    private int contador = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ingrediente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        valores_ingredientes = new javax.swing.JList<>();
        txt_precio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "mediana", "grande", "x-grande" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("TAMAÑO: ");

        jLabel2.setText("INGREDIENTES: ");

        jLabel3.setText("Ingredientes:");

        txt_ingrediente.setText("Ingredientes");

        jLabel5.setText("TOTAL: $");

        jButton1.setText("Agregar ingredientes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        valores_ingredientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Champiñones", "Peperoni", "Salami", "X-queso" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(valores_ingredientes);

        txt_precio.setText("00.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(46, 46, 46)
                                .addComponent(txt_ingrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 92, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_precio))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
         if (jComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Eliga un tamaño");
        } else {
        
        
        String ingredientes = valores_ingredientes.getSelectedValue().toString();
        int valor = valores_ingredientes.getSelectedIndex();

        boolean estatus = true;
        for (int i = 0; i < posicion.length; i++) {
            if (posicion[i] == valor) {
                estatus = false;
                break;
            }
        }
        if (estatus == true) {
            contador += 1;
            if (valor == 0) {
                double precio = pizza_.getPrice() + 7;
                pizza_.setPrice(precio);
                String valor_ing = pizza_.getIngredientes() + ingredientes;
                pizza_.setIngredientes(valor_ing);
            } else if (valor == 1) {
                double precio = pizza_.getPrice() + 10;
                pizza_.setPrice(precio);
                String valor_ing = pizza_.getIngredientes() + ingredientes;
                pizza_.setIngredientes(valor_ing);
            } else if (valor == 2) {
                double precio = pizza_.getPrice() + 12;
                pizza_.setPrice(precio);
                String valor_ing = pizza_.getIngredientes() + ingredientes;
                pizza_.setIngredientes(valor_ing);
            } else if (valor == 3) {
                double precio = pizza_.getPrice() + 12;
                pizza_.setPrice(precio);
                String valor_ing = pizza_.getIngredientes() + ingredientes;
                pizza_.setIngredientes(valor_ing);
            }
            txt_ingrediente.setText(pizza_.getIngredientes());
            txt_precio.setText("" + pizza_.getPrice());
            for (int i = 0; i < posicion.length; i++) {
                if (posicion[i] == -1) {
                    posicion[i] = valor;
                    break;
                }
            }
            
            descuento();
            
        }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        double precio = 00.00;
        if (jComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Eliga un tamaño");
           limpiar();
            precio = 0;
        } else if (jComboBox1.getSelectedIndex() == 1) {
            limpiar();
            precio = 70.00;
        } else if (jComboBox1.getSelectedIndex() == 2) {
           limpiar();
            precio = 120.00;
        } else if (jComboBox1.getSelectedIndex() == 3) {
            limpiar();
            precio = 250.00;
        }
        pizza_.setPrice(precio);
        txt_precio.setText("" + pizza_.getPrice());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void limpiar(){
     pizza_.setIngredientes("");
            pizza_.setPrice(0);
            pizza_.setSize(0);
            txt_ingrediente.setText("");
            txt_precio.setText("");
            for (int i = 0; i < posicion.length; i++) {
                posicion[i] = -1;
            }
            
            contador=0;
    }
    
    
    private void descuento(){
        double valor =0;
        pizza_.setSize(jComboBox1.getSelectedIndex());
        
        System.out.println(pizza_.getSize()  + "----" + contador);
        if (pizza_.getSize()==1 && contador > 1){
           valor = pizza_.getPrice() * 0.90;
           pizza_.setPrice(valor);
           txt_precio.setText(""+pizza_.getPrice());
            System.out.println("Descuento1");
        }else if (pizza_.getSize()==2 && contador > 2){
            System.out.println(pizza_.getPrice());
           valor = pizza_.getPrice() * 0.85;
            System.out.println(valor);
           pizza_.setPrice(valor); 
             System.out.println("Descuento2");
           txt_precio.setText(""+pizza_.getPrice());
        }else if (pizza_.getSize()==3 && contador > 3){
           valor = pizza_.getPrice() * 0.80;
           pizza_.setPrice(valor); 
             System.out.println("Descuento3");
           txt_precio.setText(""+pizza_.getPrice());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txt_ingrediente;
    private javax.swing.JLabel txt_precio;
    private javax.swing.JList<String> valores_ingredientes;
    // End of variables declaration//GEN-END:variables
}
